### PR TITLE
Update to upstream v5.14.26.1

### LINKED ISSUE #34: v5.14.26.1 Stable
Just wondering when the stable version might be updated.

### PR DESCRIPTION
**Pull request by Evanito**
Pretty much just copied over the changes from https://github.com/jkunczik/home-assistant-omada/commit/8999b31f0b205e0ea9473872677c57afa917bdc9 to the stable folder

Closes #34

### CODE REVIEW

**Comment by Evanito** [comment]
Hey @jkunczik - you around? Am I missing anything here

**Comment by Jeruntu** [comment]
Hi,
Your changes look ok, but the new docker image for Stable should be pushed to the docker registry before merging this PR.
Only @DraTrav can do this I think.

https://developers.home-assistant.io/docs/add-ons/publishing#build-scripts-to-publish-add-ons-to-a-container-registry

**Comment by Evanito** [comment]
Hmm. Maybe there is reason for some concern: https://github.com/mbentley/docker-omada-controller/issues/418#issuecomment-2294841199

**Comment by Evanito** [comment]
Should probably block this if there are issues reported on the beta version of this update, such as #33

**Comment by DraTrav** [comment]
I'll push stable to 5.13 when I am free, however 5.14 is showing a software issue that's preventing it from starting on some machines. Beta will remain on version 5.14 however and ill try to maintain it as releases come out.

**Comment by Evanito** [comment]
Closing this as next new version we should use should be at least `5.14.30.7` per https://github.com/mbentley/docker-omada-controller/issues/418#issuecomment-2294841199 and I don't want to complicate the updating by being a random third party owning this CR for no reason 👍

**Comment by DraTrav** [comment]
Was it confirmed that 5.14.30.7 fixes the booting problem?

**Pull request closed without merging**
