### PR TITLE
Implement mbentley as submodule and share common code

### PR DESCRIPTION
**Pull request by Jeruntu**
@jkunczik 

This is an improvement to PR #54

## How it works

- mbentley is now a submodule in Omada Dev
- Stable and Beta no longer contain code but just reference docker images
  - I took the idea from [Music Assistant](https://github.com/music-assistant/home-assistant-addon)
  - This makes it possible to share the same code from Omada Dev 
- Dockerfile is still unique for this Add-On and I changed it a bit for this new submodule structure to work.
  - I copy the install.sh and entrypoint-5.x.sh from mbentley
- install.sh and entrypoint.sh are basically wrapper scripts. Thanks to your restructuring this was easy.
- healthcheck.sh is now a symlink to mbently healthcheck.sh
- I had to give up the pretty logging in entrypoint.sh, but in return maintenance will be easy.
- GitHub releases are used to trigger the publishing pipeline for new docker images 
  - Stable uses `v{INSTALL_VER}-stable` as release / tag
  - Beta uses `v{INSTALL_VER}-beta` as release / tag
  - INSTALL_VER should match one of the versions in [Omada versions](https://github.com/mbentley/docker-omada-controller-url/blob/master/omada_ver_to_url.sh) and match the version in `config.yaml`.
 

## Before merging

If you like this idea, you'll have to add the following to the repository secrets:

- DOCKER_USER_NAME
- DOCKER_ACCESS_TOKEN

The image names now refer to my docker registry. You'll have to update this to the registry that we will be using, and create the needed GitHub releases on this branch, to make sure it is working. You can easily make an account on Docker Hub yourself, or I'll need the rights to add my credentials, or @DraTrav .

### CODE REVIEW

**Comment by jkunczik** [comment]
Hi @Jeruntu,
Thanks for your work! I would love to give you that access, however that is not possible for personal repsitories (see https://github.com/jkunczik/home-assistant-omada/issues/53#issuecomment-2480806749). We could open an encrypted chat somwhere to exchange that information or move this repo to an organization repository, where you could become full maintainers.

**Comment by Jeruntu** [comment]
I didn't know that wasn't possible. I created a new token and send it to your hotmail address. It is not super safe but, it is just a token that I can easily revoke when needed. Other methods look a bit like over kill to me. Please let me know if this works for you.

**Comment by jkunczik** [comment]
Thanks! I added both variables under `Secrets and Variables/Actions/Repository secrets`

**Comment by DraTrav** [comment]
This is a fantastic implementation! fantastic work! Thank you for helping out!

**Comment by DraTrav** [comment]
Though I understand why we have been using other people's Docker images, I truly believe we should use @jkunczik's Docker at some point.

**Comment by Jeruntu** [comment]
Yes, that would make more sense. The pipeline is ready for that. The only thing that is needed is to update the image in `config.yaml`, and the DOCKER_USER_NAME and DOCKER_ACCESS_TOKEN in the repository settings. And trigger the pipeline to publish new images in the registry.

**Comment by jkunczik** [comment]
As soon as I will find the time (to also deal with potential issues), I will go ahead and move the images to my Docker registry. Thank you so much @Jeruntu for your work and @DraTrav for your work keeping this project up-to-date so far!

**Pull request merged**
